name: Deploy to Nuget Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  PROJECT_PATH: 'src/ComparisonExtensions/ComparisonExtensions.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: ${{ ''https://api.nuget.org/v3/index.json'' }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }} 
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    - name: Push
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k $ {{ secrets.NUGET_API_KEY }} -s ${{ NUGET_SOURCE_URL }} 
